using Xunit;

namespace SimpleCrudApplication.EntityFrameworkCore;

[CollectionDefinition(SimpleCrudApplicationTestConsts.CollectionDefinitionName)]
public class SimpleCrudApplicationEntityFrameworkCoreCollection : ICollectionFixture<SimpleCrudApplicationEntityFrameworkCoreFixture>
{

}
