using SimpleCrudApplication.EntityFrameworkCore;
using Xunit;

namespace SimpleCrudApplication.EntityFrameworkCore;

public class SimpleCrudApplicationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SimpleCrudApplicationEntityFrameworkCoreFixture>
{

}
